name: "Test action"

inputs:
  text:
    description: "Text"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout the target repository
      uses: actions/checkout@v3
      with:
        repository: TheBusyBiscuit/composite-action-test
        fetch-depth: 0

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"

    - name: Run test script
      shell: bash
      run: |
        echo "Raw input: ${{ inputs.text }}"
        echo "Parsed input: ${{ inputs.text || 'Hello world' }}"
